---
title: "trends"
author: "daniel"
date: "July 19, 2016"
output: 
  html_document: 
    fig_width: 8
    keep_md: yes
    number_sections: yes
    toc: yes
---

```{r}
# set some stuff up
rm(list = ls())
if (interactive()) {
    data <- "sismid_10-statistics_and_modeling_with_novel_data_streams/trends/correlate-Influenza_like_Illness_CDC_.csv"
    cdc_data <- "sismid_10-statistics_and_modeling_with_novel_data_streams/trends/CDC_national_updated.csv"
} else {
    data <- "correlate-Influenza_like_Illness_CDC_.csv"
    cdc_data <- 'CDC_national_updated.csv'
}
```


```{r, message=FALSE, warning=FALSE}
library(readr)
library(lubridate)
library(dplyr)
library(glmnet)
library(useful)

ili <- read_csv(data, comment = "#", skip = 1)

 # there are 2 empty lines at the end of the file
non_empty <- apply(X = ili,
             MARGIN = 1,
             FUN = function(x){
                 ifelse(all(is.na(x)), FALSE, TRUE)
                 })
ili <- ili[non_empty, ]
ili_2 <- read.csv(data, comment.char = '#', stringsAsFactors = FALSE)
identical(ili$Date, ili_2$Date)
```

```{r}
useful::topleft(ili)
useful::topleft(ili_2)
```

# Google Coorelate

Define training period on data.
Use to predict on an out of sample testset.

```{r}
table(year(ili$Date), useNA = 'always')
```

```{r}
training_years <- c(2004:2008)
testing_years <- c(2009:2016)
```

```{r}
train_years <- ili[year(ili$Date) %in% training_years , "Date"]
test_years <- ili[year(ili$Date) %in% testing_years , "Date"]
```

```{r}
gc_training <- ili %>%
    filter(year(Date) %in% training_years) %>%
    select(-Date)
names(gc_training) <- sprintf('v%s', 1:ncol(gc_training))
gc_training <- gc_training %>% as.matrix()
topleft(gc_training)
```

```{r}
gc_testing <- ili %>%
    filter(year(Date) %in% testing_years) %>%
    select(-Date)
names(gc_testing) <- sprintf('v%s', 1:ncol(gc_testing))
gc_testing <- gc_testing %>% as.matrix()
topleft(gc_testing)
```

## Fit the model

```{r}
x <- build.x(v1 ~ . - 1, gc_training, FALSE)
y <- build.y(v1 ~ . - 1, gc_training)
```

```{r}
# set the seed
set.seed(42)

# LASSO with 5 fold cross-validation
mod_cv5 <- cv.glmnet(x = x, y = y, family = "gaussian", nfold = 5)
predictions_cv5 <- predict(mod_cv5, gc_testing[, -1])
```

## Look at model coefficients

```{r}
mod_cv5$lambda.min
mod_cv5$lambda.1se
plot(mod_cv5)
```

```{r}
#coef(mod_cv5, s="lambda.1se")
```

```{r acs-glmnet-coefficient-path,dependson='acs-glmnet-cv'}
# plot the path
plot(mod_cv5$glmnet.fit, xvar = "lambda")

# add in vertical lines for the optimal values of lambda
abline(v = log(c(mod_cv5$lambda.min, mod_cv5$lambda.1se)), lty = 2)
```

## Plot predictions

```{r, warning=FALSE}
ggplot() +
    geom_line(data = ili, aes(x = Date, y = `Influenza-like Illness (CDC)`)) +
    geom_line(aes(x = test_years, y = as.numeric(predictions_cv5)), color = 'red') +
    ggtitle('Train and Predict on Google Correlate Data')
```

# CDC Data

```{r}
cdc <- read_csv(cdc_data)
cdc$date <- as.Date(paste(cdc$YEAR, cdc$WEEK, 1, sep = '-'), "%Y-%U-%u")
names(cdc) <- c('year', 'week', 'cases', 'date')
head(cdc)
```

```{r, warning=FALSE}
ggplot() +
    geom_line(data = cdc, aes(x = date, y = as.numeric(cases))) +
    geom_line(aes(x = test_years, y = predictions_cv5), color = 'red')
```
